Updated README.md with additional instructions regarding infinitive.service
lurgh/infinitive pull request #2
Opened 2024-02-17 20:38 UTC by themrwookiee

2024-02-19 19:12 UTC, lurgh requested changes

2024-02-19 19:12 UTC, lurgh commented on README.md
> +Please note that rather than using `--` in front of each options (see below), use single `-` instead
OK, you made me look more carefully at the golang flag package docs :-) and I see that '-' and '--' are both allowed and equivalent.  So your point about '-' being required is not actually true best I can tell, and I use it just the way it's documented and it works fine; but I agree that the inconsistency between the options is not helpful, and standardizing on the way the upstreams stated it is probably fair.

So, how about you update your PR to remove this statement and change all the other references to options syntax to use the single '-'?

Just to illustrate this works for me:
```
$ ps -ef|grep infinitive
root       84087       1  3  2023 ?        2-04:21:13 /home/xxx/GIT/infinitive/infinitive -serial /dev/ttyUSB0 --rlog --mqtt=tcp:/XXX@xxx:1883
```

2024-02-19 19:12 UTC, lurgh commented on README.md
> +$ MQTTPASS=mqtt-password infinitive ... --mqtt tcp://mqtt-username@mqtt-broker-ip:1883
I suspect that your experience with the hostname not working was due to a configuration issue at your end.  I am fine with the other changes on this line but concerned about communicating that an IP is required when a hostname should work, and works fine in my testing and usage. 

Maybe check that you can resolve the hostname you were trying to use e.g. by pinging it from the same host/context where infinitive is running? Let's get to the bottom of this first.

2024-02-20 00:35 UTC, themrwookiee commented on README.md
> +Please note that rather than using `--` in front of each options (see below), use single `-` instead
That works for me!

2024-02-20 05:50 UTC, lurgh commented on README.md
> +$ MQTTPASS=mqtt-password infinitive ... -mqtt tcp://mqtt-username@mqtt-broker-ip:1883
If you don't disagree, please change the ```mqtt-broker-ip``` to ```mqtt-broker-host```.  Or if you think the hostname still doesn't work in that context, I would be happy to look into that with you.

Also, you missed one ```--rlog```, around line 467.

2024-02-20 13:20 UTC, themrwookiee commented on README.md
> +$ MQTTPASS=mqtt-password infinitive ... -mqtt tcp://mqtt-username@mqtt-broker-ip:1883
My bad, I did change it to `host` at 87 and forgot to change it back at 113. Same thing for 467

2024-02-20 18:40 UTC, lurgh approved these changes
Thanks for these changes

2024-02-20 18:40 UTC, merged